IMDB.Web/Models/MovieViewModel.cs
using IMDB.Entities.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMDB.Web.Models
{
    public class MovieViewModel
    {
        #region Fields
        private List<SelectListItem> _Actors;
        private List<SelectListItem> _Producers; 
        #endregion

        #region Constructors
        public MovieViewModel()
        {
        }

        public MovieViewModel(Movie movie)
        {
            if (movie == null)
                throw new ArgumentNullException(nameof(movie));

            MoviesName = movie.MoviesName;
            YOR = movie.YOR;
            Plot = movie.Plot;
            Poster = movie.Poster;
            ProducerId = movie.ProducerId;
        } 
        #endregion

        #region Properties
        public int MovieId { get; set; }

        [Required(ErrorMessage ="Movie name is required.")]
        public string MoviesName { get; set; }

        [Required(ErrorMessage = "Please select year of release.")]
        public int YOR { get; set; }

        [Required(ErrorMessage = "Plot is required.")]
        public string Plot { get; set; }

       // [Required(ErrorMessage ="Select the image")]
        public string Poster { get; set; }

        [Required(ErrorMessage = "Please select Producer.")]
        public int ProducerId { get; set; }

        
        public string Producer { get; set; }
        public List<int> SelectedActors { get; set; }
        public List<int> SelectedProducer { get; set; }
        
        public List<SelectListItem> Actors
        {
            get
            {
                if (_Actors == null)
                    return new List<SelectListItem>();

                return _Actors;
            }
            set
            {
                _Actors = value;
            }
        }        
        public List<SelectListItem> Producers
        {
            get
            {
                if (_Producers == null)
                    return new List<SelectListItem>();

                return _Producers;
            }
            set
            {
                _Producers = value;
            }
        }
        #endregion

        #region Methods
        public Movie ToModel()
        {
            var movie = new Movie
            {
                MoviesName = MoviesName,
                YOR = YOR,
                Plot = Plot,
                Poster = Poster,
                ProducerId = ProducerId,                
            };

            return movie;
        }

        public void UpdateEntity(Movie movie)
        {
            movie.MovieId = MovieId;
            movie.MoviesName = MoviesName;
            movie.YOR = YOR;
            movie.Plot = Plot;
            movie.Poster = Poster;
            movie.ProducerId = ProducerId;
        } 
        #endregion
    }
}

IMDB.Web/Controllers/ActorController.cs
using IMDB.Common.Interface.Repository;
using IMDB.Repository;
using IMDB.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMDB.Web.Controllers
{
    public class ActorController : Controller
    {
        private IUoWRepository _repContext = null;
        public ActorController()
            : this(new UoWRepository())
        {

        }
        public ActorController(IUoWRepository repContext)
        {
            _repContext = repContext;
        }

        // GET: Actor
        public ActionResult GetActors()
        {
            List<ActorViewModel> model = new List<ActorViewModel>();
            var actors = _repContext.ActorRep.GetActors();
            if (actors != null)
            {
                foreach (var actor in actors)
                {
                    model.Add(new ActorViewModel()
                    {
                        ActorName = actor.ActorName,
                        Gender = actor.Gender,
                        Bio = actor.Bio,
                        DOB = actor.DOB
                    });
                }
            }
            return View(model);
        }

        public ActionResult AddActor()
        {

            return View("_AddActor");
        }

        [HttpPost]
        public ActionResult AddActor(ActorViewModel model)
        {
            if (model == null)
            {
                throw new ArgumentNullException();
            }

            var errorList = new List<string>();
            if (!ModelState.IsValid)
            {
                errorList = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();
                return new JsonResult() { Data = errorList };

            }

            var duplicateActor = _repContext.ActorRep.GetActors().Count(m => m.ActorName.Trim().ToLower() == model.ActorName.Trim().ToLower());
            if (duplicateActor > 0)
            {
                ModelState.AddModelError(" ", "Actor is already in the database");
                return View(model);
            }

       

            var actor = model.ToModel();
            var result = _repContext.ActorRep.AddActor(actor);
            return new JsonResult() { Data = result };
        }
    }
}

IMDB.Web/Controllers/MovieController.cs
using IMDB.Common.Interface.Repository;
using IMDB.Entities.Models;
using IMDB.Repository;
using IMDB.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMDB.Web.Controllers
{
    [HandleError]
    public class MovieController : Controller
    {
        private IUoWRepository _repContext = null;
        public MovieController()
            : this(new UoWRepository())
        {

        }
        public MovieController(IUoWRepository repContext)
        {
            _repContext = repContext;
        }

        public ActionResult GetMovies()
        {

            List<MovieViewModel> model = new List<MovieViewModel>();
            var movies = _repContext.MoviesRep.GetMovies();
            foreach (var item in movies)
            {
                model.Add(new MovieViewModel
                {
                    MovieId = item.MovieId,
                    MoviesName = item.MoviesName,
                    YOR = item.YOR,
                    Plot = item.Plot,
                    Poster = item.Poster,
                    Producer = item.Producer.ProducerName,
                    Actors = item.Actors.Select(a => new SelectListItem
                    {
                        Text = a.ActorName,
                    }).ToList(),
                });
            }
            return View(model);
        }

        public ActionResult AddMovie()
        {
            var model = new MovieViewModel
            {
                Actors = GetActors(),
                Producers = GetProducers()
            };

            return View("AddMovie", model);
        }

        [HttpPost]
        public ActionResult AddMovie(MovieViewModel model, HttpPostedFileBase fileUpload)
        {
            if (model == null)
            {
                throw new ArgumentNullException();
            }

            model.Actors = GetActors();
            model.Producers = GetProducers();

            var errorList = new List<string>();

            string filePath = string.Empty;
            if (fileUpload != null)
            {

                string fileName = Path.GetFileName(Guid.NewGuid() + fileUpload.FileName).ToString();
                filePath = Path.Combine(Server.MapPath("~/UploadedFile/"), fileName);
                fileUpload.SaveAs(filePath);

                var index = filePath.IndexOf("UploadedFile");
                model.Poster = "~\\" + filePath.Substring(index);
            }


            if (!ModelState.IsValid)
            {
                errorList = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();
                return View(model);
            }

            var duplicateMovie = _repContext.MoviesRep.GetMovies().Count(m => m.MoviesName.Trim().ToLower() == model.MoviesName.Trim().ToLower());
            if (duplicateMovie > 0)
            {
                ModelState.AddModelError(" ", "Movie is already in the database");
                return View(model);
            }


            var movie = model.ToModel();
            movie.Actors = GetActors(model.SelectedActors);
            var result = _repContext.MoviesRep.AddMovie(movie);
            return RedirectToAction("GetMovies");
        }


        public ActionResult EditMovie(int movieId)
        {
            if (movieId <= 0)
            {
                return View(new MovieViewModel());
            }

            var movie = _repContext.MoviesRep.GetMovieById(movieId);

            if (movie == null)
            {
                return HttpNotFound();
            }

            var map = movie.Actors.ToDictionary(a => a.ActorId.ToString(), a => a);
            var allActors = GetActors();
            Actor actorEntity;
            foreach (var actor in allActors)
            {
                if (map.TryGetValue(actor.Value, out actorEntity))
                {
                    actor.Selected = true;
                }
            }

            MovieViewModel model = new MovieViewModel(movie)
            {
                Producers = GetProducers(),
                Actors = allActors,
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult EditMovie(MovieViewModel model, HttpPostedFileBase fileUpload)
        {
            var actors = new MovieViewModel { Actors = GetActors() };
            var movie = _repContext.MoviesRep.GetMovieById(model.MovieId);
            if (movie == null)
            {
                return HttpNotFound();
            }

            var errorList = new List<string>();
            if (!ModelState.IsValid)
            {
                errorList = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();
                return View(model);
            }


            var duplicateMovie = _repContext.MoviesRep.GetMovies().Count(m => m.MoviesName.Trim().ToLower() == model.MoviesName.Trim().ToLower());
            if (duplicateMovie > 1)
            {
                ModelState.AddModelError(" ", "Movie is already in the database");
                return View(model);
            }

            string filePath = string.Empty;

            if (fileUpload != null)
            {
                string fileName = Path.GetFileName(fileUpload.FileName);
                filePath = Path.Combine(Server.MapPath("~/UploadedFile"), fileName);
                fileUpload.SaveAs(filePath);
                var index = filePath.IndexOf("UploadedFile");
                model.Poster = "~\\" + filePath.Substring(index);
            }

            AddOrUpdateKeepExistingActors(movie, model);
            model.UpdateEntity(movie);
            movie.Actors = GetActors(model.SelectedActors);

            var result = _repContext.MoviesRep.EditMovie(movie);

            return RedirectToAction("GetMovies");
        }

  

        [HttpPost]
        public ActionResult DeleteMovie(int movieId)
        {
            if (movieId <= 0)
            {
                return HttpNotFound("Movie not found with this id." + movieId);
            }
            var result = _repContext.MoviesRep.DeleteMovie(movieId);
            return RedirectToAction("GetMovies");
        }

        private void AddOrUpdateKeepExistingActors(Movie movie, MovieViewModel movieViewModel)
        {
            //TODO: Extention to parst int
            var webSelectedActors = movieViewModel.Actors.Where(c => c.Selected).Select(a => int.Parse(a.Value)).ToList();
            var dbActors = movie.Actors.Select(a => a.ActorId).ToList();
            //TODO: Need a null check on web and dbActors

            var coursesToDeleteIDs = dbActors.Where(id => !webSelectedActors.Contains(id)).ToList();
            var allDbActors = _repContext.ActorRep.GetActors();
            if (allDbActors == null)
                return;
            var actorMap = allDbActors.ToDictionary(a => a.ActorId, a => a);
            // Delete removed courses
            Actor actor;
            foreach (var id in coursesToDeleteIDs)
            {
                if (actorMap.TryGetValue(id, out actor))
                {
                    movie.Actors.Remove(actor);
                }
            }

            // Add courses that user doesn't already have
            foreach (var id in webSelectedActors)
            {
                if (!dbActors.Contains(id))
                {
                    if (actorMap.TryGetValue(id, out actor))
                    {
                        movie.Actors.Add(actor);
                    }
                }
            }
        }

        private List<Actor> GetActors(List<int> ids)
        {
            if (ids == null)
            {
                return new List<Actor>();
            }
            var actors = _repContext.ActorRep.GetActors(ids);
            return actors;
        }

        private List<SelectListItem> GetActors()
        {
            var actors = _repContext.ActorRep.GetActors();
            if (actors == null)
            {
                return new List<SelectListItem>();
            }
            var actorVM = actors.Select(a => new SelectListItem
            {
                Value = a.ActorId.ToString(),
                Text = a.ActorName,
            }).ToList();
            return actorVM;
        }

        private List<SelectListItem> GetProducers()
        {
            var producer = _repContext.ProducerRep.GetProducer();
            if (producer == null)
            {
                return new List<SelectListItem>();
            }
            var producerVM = producer.Select(a => new SelectListItem
            {
                Value = a.ProducerId.ToString(),
                Text = a.ProducerName,
            }).ToList();
            return producerVM;
        }
    }

}

IMDB.Web/Controllers/ProducerController.cs
using IMDB.Common.Interface.Repository;
using IMDB.Repository;
using IMDB.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMDB.Web.Controllers
{
    public class ProducerController : Controller
    {

        private IUoWRepository _repContext = null;
        public ProducerController()
            : this(new UoWRepository())
        {

        }
        public ProducerController(IUoWRepository repContext)
        {
            _repContext = repContext;
        }

        public ActionResult GetProducers()
        {
            List<ProducerViewModel> model = new List<ProducerViewModel>();
            var producers = _repContext.ProducerRep.GetProducer();
            if (producers != null)
            {
                foreach (var producer in producers)
                {
                    model.Add(new ProducerViewModel()
                    {
                        ProducerName = producer.ProducerName,
                        ProducerGender = producer.Gender,
                        ProducerBio = producer.Bio,
                        ProducerDOB = producer.DOB
                    });
                }
            }
            return View(model);
        }

        public ActionResult AddProducer()
        {
            return View("_AddProducer");
        }

        [HttpPost]
        public ActionResult AddProducer(ProducerViewModel model)
        {
            if (model == null)
            {
                throw new ArgumentNullException();
            }
            var errorList = new List<string>();
            if (!ModelState.IsValid)
            {
                errorList = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();
                return new JsonResult() { Data = errorList };

            }

            var duplicateProducer = _repContext.ProducerRep.GetProducer().Count(m => m.ProducerName.Trim().ToLower() == model.ProducerName.Trim().ToLower());
            if (duplicateProducer > 0)
            {
                ModelState.AddModelError(" ", "Producer is already in the database");
                return View(model);
            }

            var actor = model.ToModel();
            var result = _repContext.ProducerRep.AddProducer(actor);
            return new JsonResult() { Data = result };
        }
    }
}

IMDB.Web/Views/Movie/AddMovie.cshtml
@model IMDB.Web.Models.MovieViewModel
@using IMDB.Web.Models

@{
    ViewBag.Title = "Add Movie";
}



<div class="container">

    @using (Html.BeginForm("AddMovie", "Movie", FormMethod.Post, new { id = "frmSaveMovie", @class = "well form-horizontal", enctype = "multipart/form-data" }))
    {
        <fieldset>
            <legend>Add the movie!</legend>
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(false, "", new { @class = "text-danger" })


            <div class="form-group">
                <label class="col-md-4 control-label">Movie Name</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        @Html.EditorFor(model => model.MoviesName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Movie Name", @name = "name" } })
                        @*@Html.ValidationMessageFor(model => model.MoviesName, "", new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Year Of release</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        @Html.EditorFor(model => model.YOR, new { htmlAttributes = new { @class = "form-control", @placeholder = "Year of release", @name = "yor" } })
                        @*@Html.ValidationMessageFor(model => model.YOR, "", new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-4 control-label">Plot</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        @Html.EditorFor(model => model.Plot, new { htmlAttributes = new { @class = "form-control", @placeholder = "Plot", @name = "plot" } })
                        @*@Html.ValidationMessageFor(model => model.Plot, "", new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Poster</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <input type="file" id="fileUpload" name="fileUpload" size="23" class="form-control" accept="image/png, image/jpeg" />
                        @*@Html.ValidationMessageFor(model => model.Poster, "", new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>



            <div class="form-group">
                <label class="col-md-4 control-label">Producer</label>
                <div class="col-md-4 selectContainer">
                    <div class="input-group">
                        @Html.DropDownListFor(m => m.ProducerId, Model.Producers, "Please Select Producer", new { htmlAttributes = new { @class = "form-control selectpicker" } })
                        @*@Html.ValidationMessageFor(model => model.ProducerId, "", new { @class = "text-danger" })*@

                        <button type="button" class="btn btn-info" id="addProducer">
                            <span class="glyphicon glyphicon-plus-sign pull-right"></span> Add Producer
                        </button>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Select Actors</label>

                <button type="button" class="btn btn-info" id="addActor">
                    <span class="glyphicon glyphicon-plus-sign pull-right"></span> Add Actor
                </button>
                <div class="col-md-4 selectContainer">
                    <div class="input-group">
                        <div id="js-actors">
                            @if (Model.Actors?.Count > 0)
                            {

                                foreach (var item in Model.Actors)
                                {
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"
                                                   name="SelectedActors"
                                                   value="@item.Value" /> @item.Text
                                            </label>
                                        </div>
                                }

                            }
                        </div>

                    </div>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-warning">Save <span class="glyphicon glyphicon-send"></span></button>
                </div>
            </div>

        </fieldset>
    }
</div>


<div class="modal fade" id="actorModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Actor</h4>
            </div>
            <div class="modal-body">
                @{ Html.RenderPartial("_AddActor", new ActorViewModel());}
            </div>
            <div class="modal-footer">
                <button type="button" id="closeActorModal" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="saveActor" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="producerModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Producer</h4>
            </div>
            <div class="modal-body">
                @{ Html.RenderPartial("_AddProducer", new ProducerViewModel());}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="closeProducerModal" data-dismiss="modal">Close</button>
                <button type="button" id="saveProducer" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <script type="text/javascript">

        // for actor modal
        $(function () {
            var url = '@Url.Action("AddActor", "Actor")';

            $('#addActor').click(function () {
                $('#actorModel').modal('toggle');
            })


            var items = [];
            var data = {};
            $("#errorActor").hide();
            $('#saveActor').on('click', function onSave() {
                data.ActorName = $('#js-actor-name').val();
                data.DOB = $('#js-actor-dob').val();
                data.Bio = $('#Bio').val();
                data.gender = $('#Gender Option:selected').text();
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: data,
                }).success(function (result) {
                    if (result > 1) {
                        $('#actorModel').modal('toggle');
                        var template = '<div class="checkbox">' + '<label>' +
                            '<input type="checkbox"' +
                                    'name="SelectedActors"' +
                                    'value="' + result + '"></input>' + data.ActorName + '</label>' + ' </div>';
                    }
                    else {
                        $("#errorActor").show();
                        for (var i = 0, error = result; i < error.length; i++) {
                            items.push('<li style="color: #b94a48">' + error[i] + '</li>')
                        };
                        $('#errorDisplayActor').append(items.join(''));
                    }

                    $('#js-actors').append(template);
                    $('#js-actor-name').val("");
                    $('#js-actor-dob').val("");
                    $('#Bio').text("");

                }).error(function (error) {

                });
            })
        })

        $('#closeActorModal').on('click', function onSave() {
            $("#errorActor").hide();
            $('#errorDisplayActor').html("");
        })




        // for producer modal
        $(function () {
            var url = '@Url.Action("AddProducer", "Producer")';
            $("#errorProducer").hide();
            $('#addProducer').click(function () {
                $('#errorDisplayProducer').text("");
                $('#producerModel').modal('toggle');
            })

            var items = [];
            var ProducerData = {};

            $('#saveProducer').on('click', function onSave(e) {

                ProducerData.ProducerName = $('#js-producer-name').val();
                ProducerData.ProducerDOB = $('#js-producer-dob').val();
                ProducerData.ProducerBio = $('#ProducerBio').val();
                ProducerData.ProducerGender = $('#ProducerGender Option:selected').text();
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: ProducerData,
                }).success(function (result) {

                    if (result > 0) {
                        $('#producerModel').modal('toggle');
                        $("#ProducerId").append($("<option     />").val(result).text(ProducerData.ProducerName));
                        $('#errorDisplayProducer').html("");
                    } else {

                        $("#errorProducer").show();
                        for (var i = 0, error = result; i < error.length; i++) {
                            items.push('<li style="color: #b94a48">' + error[i] + '</li>')
                        };
                        $('#errorDisplayProducer').append(items.join(''));
                    }
                    $('#js-producer-name').val("");
                    $('#js-producer-dob').val("");
                    $('#ProducerBio').val("");

                }).error(function (error) {

                });
            })
        });


        $('#closeProducerModal').on('click', function onSave() {
            $("#errorProducer").hide();
            $('#errorDisplayProducer').text("");
        })

        $(function () {
            $("#js-actor-dob").datepicker({
                dateFormat: 'yy-mm-dd'
            });
        });
        $(function () {
            $("#js-producer-dob").datepicker({
                dateFormat: 'yy-mm-dd'
            });
        });



        // only year

        $(function () {
        
            $('#YOR').datepicker({ dateFormat: 'yy' })
        });
       
    </script>
}
<style>
    /*.ui-datepicker-calendar { display: none; }*/
</style>